PUBLIC PRINT_UD_NUM
PUBLIC PRINT_SH_NUM

EXTRN NUMBER : WORD

DSEG SEGMENT PARA PUBLIC 'DATA'
	MASK2 DW 1
	MASK16 DW 15
	CNV_MSG DB 13, 10, 13, 10, "Converted number: $"
	BUFFER DB 20 DUP('$')
DSEG ENDS

CSEG SEGMENT PARA PUBLIC 'CODE'
	ASSUME DS:DSEG, CS:CSEG

PRINT_UD_NUM PROC NEAR

	MOV SI, 1 ;Счетчик степени
	MOV BX, 16 ;Счетчик цикла
	MOV DI, 0 ;Переведенное число
	MOV CX, NUMBER
	
	CONVERT:
		MOV DX, CX
		AND DX, MASK2
		
		MOV AX, SI
		MUL DL
		ADD DI, AX
		
		MOV AX, SI
		MOV DX, 2
		MUL DX
		MOV SI, AX
		SHR CX, 1
		DEC BX
		JNZ CONVERT
		
	MOV AX, DI
	MOV CX, 10
	MOV SI, 0
	
	digit_to_symb:
		XOR DX, DX
		DIV CX
		XCHG AX, DX
		ADD AL, '0'
		MOV BUFFER[SI], AL
		INC SI
		XCHG AX, DX
		OR AX, AX
		JNE digit_to_symb

	MOV AH, 09h
	MOV DX, OFFSET CNV_MSG
	INT 21h
	MOV DX, OFFSET BUFFER
	INT 21H
	
	RET
PRINT_UD_NUM ENDP

PRINT_SH_NUM PROC NEAR
	RET
PRINT_SH_NUM ENDP

CSEG ENDS
END